insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(1716, 1, 'RUA ARNO LINKE 91','','', 98338000, '', 'NOVO BARREIRO');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(1397, 1, 'VALENTIN STEFANELLO 264','','', 98350000, '', 'JABOTICABA');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(1861, 1, 'BORGES DE MEDEIROS, 1597','','', 98345000, '', 'PINHAL');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(2395, 1, 'LINHA PASSINHO DA CRUZ, 2800','','', 98323000, '', 'SÃO PEDRO DAS MISSÕES');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(2411, 1, 'KM 15 - BR 468','','', 98300000, '', 'PALMEIRA DAS MISSÕES');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(1889, 1, 'HILDEBRANDO AMARAL E SILVA 100','','', 98335000, '', 'JABOTICABA');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(2802, 1, 'POTREIRO BONITO KM 5','','', 89300000, '', 'PALMEIRA DAS MISSÕES');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(1612, 1, 'INDENPEDÊNCIA, 2388','','', 98300000, '', 'PALMEIRA DAS MISSÕES');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(343, 1, 'CEL. EVARISTO, S/Nº','','', 98300000, '', 'PALMEIRA DAS MISSÕES');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(1897, 1, 'LOC. RINCÃO DOS FORTES, S/Nº','','', 98385000, '', 'DOIS IRMÃOS DAS MISSÕES');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(1182, 1, 'ESQUINA SÃO BENTO','','', 98300000, '', 'PALMEIRA DAS MISSÕES');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(364, 1, 'CAPITÃO BALBINO, 945','','', 98390000, '', 'ERVAL SECO');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(1799, 1, 'FAZ. SAMPAIO ESQ. SCHERER','','', 98300000, '', 'PALMEIRA DAS MISSÕES');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(2197, 1, 'RUA AGENOR DE BARROS 290','','', 98300000, '', 'PALMEIRA DAS MISSÕES');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(1396, 1, 'BELA VISTA','','', 98338000, '', 'NOVO BARREIRO');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(213, 1, 'R. DAVI CANABARRO 110','','', 99380000, '', 'SEBERI');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(1915, 1, 'JEOVANE AGUIAR FREITAS 100','','', 98385000, '', 'DOIS IRMÃOS DAS MISSÕES');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(2389, 1, 'RUA RIO BRANCO, 511','','', 98300000, '', 'PALMEIRA DAS MISSÕES');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(2321, 1, 'RUA NELSON MARTINELLI, 516','','', 98330000, '', 'SAGRADA FAMÍLIA');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(344, 1, 'MAXIMILIANO BESENDREN, S/Nº','','', 98300000, '', 'PALMEIRA DAS MISSÕES');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(2117, 1, 'RUA CORONEL EVARISTO 2380','','', 98300000, '', 'PALMEIRA DAS MISSÕES');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(345, 1, 'RUA DA REPUBLICA, 171','','', 98300000, '', 'PALMEIRA DAS MISSÕES');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(1104, 1, 'RUA 15 DE NOVEMBRO 375','','', 98290000, '', 'CONDOR');
insert into endereço (end_id, tipo_end, logradouro, numero, bairro, cep, uf, cidade)  values(1960, 1, 'BR 386 - KM 71','','', 98335000, '', 'BOA VISTA DAS MISSÕES');
